### ISSUE TITLE
Configure GA in _config.yml

### ISSUE THREAD

**Issue by agnessa** [Vizzuality/playbook#1]

**Comment by Jamie-Gibson** [comment]
I created a property within the Vizzuality account for you


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-6363508-16"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-6363508-16');
</script>

**Comment by agnessa** [comment]
thank you, applied!
