### ISSUE TITLE
Recommendation for guidelines

### ISSUE THREAD

**Issue by agnessa** [Vizzuality/playbook#5]
[Extracted from #4 ]

Should we ad some "guidelines for guideline creation"?

Things like them being specific and actionable? something about tone? or can we do that as we go?

**Comment by agnessa** [comment]
@d4weed I'm not sure this format will work for all content, especially for the 5 systems that we'll be starting with. Maybe this is not what you have in mind, but I wanted to share my thoughts on how to communicate the core governance content. I think it should be a "good read", engaging and inspiring, with examples and graphics, explaining how we want to work here in a way that works for a newcomer. This is a good example of what I have in mind: https://steamcdn-a.akamaihd.net/apps/valve/Valve_NewEmployeeHandbook.pdf

Here is another example, which I believe describes everything in much greater detail, but must be a tough read for a newcomer as there seems to be just too much of everything: https://legacy.gitbook.com/book/enspiral/enspiral-handbook/details

I think there's value in separating the core governance systems and operational guidelines in terms of content organisation and format. An operational guideline could hopefully be a much shorter read. I wonder if the information flow team have opinions on that.

**Comment by d4weed** [comment]
I agree, and was actually thinking about having a separate thing for core governance, and keep this for things like hiring process, submitting invoices, vacation, etc

Is that what you meant?

It could still be a nice exercise trying to fit them within the systems, but if they don't fit we can always create ad-hoc sections

(btw, I hadn't seen this until now, sorry)

**Comment by d4weed** [comment]
@agnessa I've been thinking about this and although we could theoretically fit most of the operational guidelines under the systems, it doesn't seem to be the best way as a couple of them (resource-allocation and communication flows) would gather most of the content, while the others would be very small in comparison.

Also, I see things like "onboarding guidelines" sitting awkwardly somewhere between communication and resources without really fitting into any of them.

A possibility would be to organize the operational guidelines in a different way. We could, for example, do it temporally, starting with general descriptions, hiring guidelines, onboarding, tools, compensation, expenses and so on (loosely following a pattern of what people would need to know first)

The other issue is if we keep both core and operational in this playbook (but clearly separated, and perhaps with different tones) or not

What do you think?

**Comment by agnessa** [comment]
I agree it's not worth trying to fit everything into these fixed categories. The more I think about it the more it seems to me that we should now be merging the 5 systems into a single, consistent narrative, and start a new classification scheme for operational guidelines, so that e.g. onboarding is allowed to become a category of its own. As to where to keep them, I'd apply Ockham's razor for now and stick to this playbook until we have enough mature content to decide a split is needed.

**Comment by agnessa** [comment]
Closed by #7
